# Generated by Django 4.1 on 2022-09-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('watched', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('release_date', models.CharField(max_length=255))
                ('review', models.TextField())
            ],
        ),
    ]
